### ISSUE TITLE
how can I extract emails from the list of website?

### ISSUE THREAD

**Issue by mohammed-sec2010** [dmitriiweb/extract-emails#3]
Hello
how can I extract emails from the list of website by using your tool?

thanks

**Comment by dmitriiweb** [comment]
`
websites =[list of urls]
emails = [ExtractEmails(url).emails for url in websites]
`

**Comment by dabeer445** [comment]
```
from extract_emails import *
emails = [ExtractEmails(url).emails for url in ['xyv.com']]
```

Error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
NameError: name 'ExtractEmails' is not defined

```

Can you please help me out here?

**Comment by dmitriiweb** [comment]
Hi @dabeer445, it's easy:
```
from extract_emails.browsers.requests_browser import RequestsBrowser as Browser
from extract_emails import DefaultFilterAndEmailFactory as Factory
from extract_emails import DefaultWorker

browser = Browser()
urls = ['1.com', '2.com']

for url in urls:
    factory = Factory(website_url=url, browser=browser)
    worker = DefaultWorker(factory)
    data = worker.get_data()
```

**Comment by dabeer445** [comment]
Thanks a lot, there was an issue in the installed versions!
