### ISSUE TITLE
Error when running code

### ISSUE THREAD

**Issue by okofishe** [dmitriiweb/extract-emails#37]
Hello,
after pip install extract_emails  and trying to run your sample code i got the error below.  What could be the problem. Thanks in advance and between pip install extract_emails[all] is not working, why?

Traceback (most recent call last):
  File "/Users/user/My Drive/emailextractfromURL/olu.py", line 3, in <module>
    from extract_emails import DefaultFilterAndEmailFactory as Factory
  File "/Users/user/My Drive/emailextractfromURL/venv/lib/python3.9/site-packages/extract_emails/__init__.py", line 2, in <module>
    from .factories import (
  File "/Users/user/My Drive/emailextractfromURL/venv/lib/python3.9/site-packages/extract_emails/factories/__init__.py", line 1, in <module>
    from .base_factory import BaseFactory
  File "/Users/user/My Drive/emailextractfromURL/venv/lib/python3.9/site-packages/extract_emails/factories/base_factory.py", line 6, in <module>
    from extract_emails.link_filters import LinkFilterBase
  File "/Users/user/My Drive/emailextractfromURL/venv/lib/python3.9/site-packages/extract_emails/link_filters/__init__.py", line 1, in <module>
    from .contact_link_filter import ContactInfoLinkFilter
  File "/Users/user/My Drive/emailextractfromURL/venv/lib/python3.9/site-packages/extract_emails/link_filters/contact_link_filter.py", line 7, in <module>
    class ContactInfoLinkFilter(LinkFilterBase):
  File "/Users/user/My Drive/emailextractfromURL/venv/lib/python3.9/site-packages/extract_emails/link_filters/contact_link_filter.py", line 53, in ContactInfoLinkFilter
    contruct_candidates: list[str] | None = None,
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'

**Comment by Praveensenpai** [comment]
which python version are u using?

**Comment by dsldsl** [comment]
i get this error in 3.9.20
