### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by FormationGrowthHacking** [dmitriiweb/extract-emails#4]
Hi,

Thanks for your work.

I installed and followed your instruction. I get these errors:
```
Traceback (most recent call last):
  File "C:/Users/Nino/PycharmProjects/EmailVerif/emailverif.py", line 8, in <module>
    em = ExtractEmails(url, depth=None, print_log=False, ssl_verify=True, user_agent=None, request_delay=0.0)
  File "C:\Users\Nino\PycharmProjects\EmailVerif\venv\lib\site-packages\extract_emails\extract_emails.py", line 31, in __init__
    self.extract_emails(url)
  File "C:\Users\Nino\PycharmProjects\EmailVerif\venv\lib\site-packages\extract_emails\extract_emails.py", line 38, in extract_emails
    self.get_emails(r.text)
  File "C:\Users\Nino\PycharmProjects\EmailVerif\venv\lib\site-packages\extract_emails\extract_emails.py", line 53, in get_emails
    domains = self.get_domains()
  File "C:\Users\Nino\PycharmProjects\EmailVerif\venv\lib\site-packages\extract_emails\extract_emails.py", line 61, in get_domains
    with open(DOMAINS_FAIL, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Nino\\PycharmProjects\\EmailVerif\\venv\\lib\\site-packages\\extract_emails\\top_level_domains.pkl'

Process finished with exit code 1
```

Could you provide the missing file please?

Kind regards

**Comment by dmitriiweb** [comment]
Hi,
top_level_domains.pkl - what is this?

**Comment by FormationGrowthHacking** [comment]
No idea!
  
  
  
  Cordialement     

  
Gauthier Buttez
  
  
Centre de formation France
 EURL SIREN:831 709 431 (tel:831%20709%20431)
   44 rue Montmejean
 33100 Bordeaux - FRANCE (http://maps.google.com/?q=44%20rue%20Montmejean%20Bordeaux)
   Email (http://centredeformationfrance.com/contacts/uncategorised/contact)
   Tel: +33(0)7 67 37 17 15   (tel:+33767371715)(   whatsapp (whatsapp://send?text=Hi&phone=+33647023125&abid=+33647023125),   Line (line://msg/text=Hi&phone=+33647023125&abid=+33767371715), Viber)         
  

  
  
>

**Comment by dmitriiweb** [comment]
Hi,
Thanks for your message.
Please run: pip install -U extract-emails

**Comment by FormationGrowthHacking** [comment]
Thank you so much.

**Comment by dmitriiweb** [comment]
You are welcome.
